In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df=sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
import numpy as np
import pandas as pd

x = np.mean(df['total_bill'])   # mean
y = np.std(df['total_bill'])    # standard deviation

listy = list(df['total_bill'])

newx = []
for i in listy:
    z = (i - x) / y
    newx.append(z)

df1 = pd.DataFrame(newx, columns=['total_bill_zscore'])
df1

     total_bill_zscore
0            -0.314711
1            -1.063235
2             0.137780
3             0.438315
4             0.540745
..                 ...
239           1.040511
240           0.832275
241           0.324630
242          -0.221287
243          -0.113229

[244 rows x 1 columns]

In [4]:
x = np.mean(df['total_bill'])   # mean
y = np.std(df['total_bill'])    # standard deviation

zdata = (df['total_bill'] - x) / y
standraded=pd.DataFrame(zdata)
standraded

     total_bill
0     -0.314711
1     -1.063235
2      0.137780
3      0.438315
4      0.540745
..          ...
239    1.040511
240    0.832275
241    0.324630
242   -0.221287
243   -0.113229

[244 rows x 1 columns]

In [5]:
from sklearn.preprocessing import MinMaxScaler
cols = ['total_bill', 'tip']

scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])

df.head()

   total_bill       tip     sex smoker  day    time  size
0    0.291579  0.001111  Female     No  Sun  Dinner     2
1    0.152283  0.073333    Male     No  Sun  Dinner     3
2    0.375786  0.277778    Male     No  Sun  Dinner     3
3    0.431713  0.256667    Male     No  Sun  Dinner     2
4    0.450775  0.290000  Female     No  Sun  Dinner     4

In [6]:
df['total_bill_norm'] = (
    df['total_bill'] - df['total_bill'].min()
) / (
    df['total_bill'].max() - df['total_bill'].min()
)
df.total_bill_norm

0      0.291579
1      0.152283
2      0.375786
3      0.431713
4      0.450775
         ...
239    0.543779
240    0.505027
241    0.410557
242    0.308965
243    0.329074
Name: total_bill_norm, Length: 244, dtype: float64

In [7]:
cols = ['total_bill', 'tip']

df[cols] = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df[cols]

     total_bill       tip
0      0.291579  0.001111
1      0.152283  0.073333
2      0.375786  0.277778
3      0.431713  0.256667
4      0.450775  0.290000
..          ...       ...
239    0.543779  0.546667
240    0.505027  0.111111
241    0.410557  0.111111
242    0.308965  0.083333
243    0.329074  0.222222

[244 rows x 2 columns]