In [285]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [286]:
df=sns.load_dataset('mpg')
# from sklearn.datasets import mpg uf ther is one of such type

In [287]:
df.drop("name",axis=1,inplace=True)

In [288]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [289]:
df.shape

(398, 8)

In [290]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [291]:
x=df['horsepower'].median()
x

np.float64(93.5)

In [292]:
#df['horsepower']=df['horsepower'].replace({'0':'x'})  wrong because 0,null,nan,NaN etc are present

In [293]:
df['horsepower']=df['horsepower'].fillna(x)

In [294]:
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [295]:
df.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [296]:
df['origin'].map({'usa':0,'japan':1,'europe':2})

0      0
1      0
2      0
3      0
4      0
      ..
393    0
394    2
395    0
396    0
397    0
Name: origin, Length: 398, dtype: int64

In [297]:
df['origin'].replace({
                      'usa':1,
                      'japan':2,
                      'europe':3},inplace=True)

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [299]:
df.origin=df.origin.astype(float)
df.origin.value_counts()

origin
1.0    249
2.0     79
3.0     70
Name: count, dtype: int64

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 25.0 KB

In [301]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [302]:
df1=df.drop('mpg',axis=1)
x=df1
y=df.mpg

In [303]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1.0
1,8,350.0,165.0,3693,11.5,70,1.0
2,8,318.0,150.0,3436,11.0,70,1.0
3,8,304.0,150.0,3433,12.0,70,1.0
4,8,302.0,140.0,3449,10.5,70,1.0
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1.0
394,4,97.0,52.0,2130,24.6,82,3.0
395,4,135.0,84.0,2295,11.6,82,1.0
396,4,120.0,79.0,2625,18.6,82,1.0
397,4,119.0,82.0,2720,19.4,82,1.0

In [304]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [305]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

In [306]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [360]:
#model=RFE(linear regression,no_....fetures=6

In [307]:
lr.fit(x_train,y_train)

LinearRegression()

In [308]:
x_train.columns

Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model_year', 'origin'],
      dtype='object')

In [309]:
lr.coef_*100

array([-31.76142303,   2.62374826,  -1.82707649,  -0.74877504,
         5.04067346,  84.70951427, 151.90958388])

In [310]:
for i,col_name in enumerate(x_train.columns):
    print(f"the values of coef for {col_name} is {lr.coef_[i]*100}")

the values of coef for cylinders is -31.76142302799355
the values of coef for displacement is 2.623748259907893
the values of coef for horsepower is -1.8270764913124602
the values of coef for weight is -0.7487750398361896
the values of coef for acceleration is 5.04067346197135
the values of coef for model_year is 84.70951427061368
the values of coef for origin is 151.9095838797505

In [311]:

lr.intercept_

np.float64(-23.08538074231669)

In [312]:
for i, coef in zip(x_train.columns, lr.coef_):
    print(f"The coefficient for {i} is {coef*100}")

The coefficient for cylinders is -31.76142302799355
The coefficient for displacement is 2.623748259907893
The coefficient for horsepower is -1.8270764913124602
The coefficient for weight is -0.7487750398361896
The coefficient for acceleration is 5.04067346197135
The coefficient for model_year is 84.70951427061368
The coefficient for origin is 151.9095838797505

In [313]:
from sklearn.metrics import r2_score
y_test_predict=lr.predict(x_test)
y_train_predict=lr.predict(x_train)

In [314]:
r2_linear_test=r2_score(y_test,y_test_predict)
r2_linear_test

0.8348001123742286

In [315]:
r2_linear_train=r2_score(y_train,y_train_predict)
r2_linear_train

0.8125585856350536

In [316]:
from sklearn.linear_model import Ridge
rig_model=Ridge(alpha=.1)

In [317]:
rig_model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [318]:
for i, coef in zip(x_train.columns, rig_model.coef_):
    print(f"The coefficient for {i} is {coef*100}")

The coefficient for cylinders is -31.70032101006609
The coefficient for displacement is 2.6213249757982955
The coefficient for horsepower is -1.8263252481448862
The coefficient for weight is -0.748732605021311
The coefficient for acceleration is 5.036896947442607
The coefficient for model_year is 84.70062938903142
The coefficient for origin is 151.7452828565376

In [319]:
# for ridge regression evalutation 
y_predict_ridge=rig_model.predict(x_test)
rig_r2_score=r2_score(y_test,y_predict_ridge)
rig_r2_score

0.8348084889168357

In [320]:
r2_linear_test
# small diffrence in values ..mino changes at end

0.8348001123742286

In [321]:
from sklearn.linear_model import Lasso
lso=Lasso(alpha=.5)
lso

Lasso(alpha=0.5)

In [322]:
lso.fit(x_train,y_train)

Lasso(alpha=0.5)

In [323]:
y_test_predict_lso=lso.predict(x_test)

In [324]:
lso_r2_score=r2_score(y_test,y_test_predict_lso)
lso_r2_score

0.8277934716635555

In [325]:
for i, coef in zip(x_train.columns, lso.coef_):
    print(f"The coefficient for {i} is {coef*100}")

The coefficient for cylinders is 0.0
The coefficient for displacement is 0.6208198888300324
The coefficient for horsepower is -1.105838298716962
The coefficient for weight is -0.6982673168023082
The coefficient for acceleration is 0.0
The coefficient for model_year is 74.46549520038187
The coefficient for origin is 0.0

In [326]:
# 3 featurees becomes zero thefore 
# lasoo help i feature selection

In [327]:
from sklearn.linear_model import ElasticNet
ets=ElasticNet(alpha=1,l1_ratio=.5)
ets

ElasticNet(alpha=1)

In [328]:
ets.fit(x_train,y_train)
y_test_predict_ets=ets.predict(x_test)
ets_r2_score=r2_score(y_test,y_test_predict_ets)
ets_r2_score

0.8284840073256803

In [329]:
for i, coef in zip(x_train.columns, ets.coef_):
    print(f"The coefficient for {i} is {coef*100}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.5888869953667496
The coefficient for horsepower is -1.2403874933570151
The coefficient for weight is -0.6934550516257623
The coefficient for acceleration is 0.0
The coefficient for model_year is 71.33150744603871
The coefficient for origin is 0.0

In [330]:
from sklearn.linear_model import LassoCV
lcv=LassoCV(cv=5,verbose=1)
lcv

LassoCV(cv=5, verbose=1)

In [331]:
# cv with hyperparamter tuning

In [332]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.linear_model import Lasso,Ridge

In [333]:
lso=Lasso()
lso

Lasso()

In [334]:
param_grid={'alpha':[0.001,.01,.1,1,10,100]}
param_grid

{'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}

In [335]:
grid_search=GridSearchCV(estimator=lso,param_grid=param_grid,cv=5,scoring='r2',verbose=2)
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [336]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [337]:
grid_search.best_params_

{'alpha': 0.1}

In [338]:
grid_search.best_score_

np.float64(0.7964209726696481)

In [339]:
grid_search.best_estimator_

Lasso(alpha=0.1)

In [340]:
y_predict_lso=grid_search.best_estimator_.predict(x_test)
r2_score(y_test,y_predict_lso)

0.8345318641232302

In [341]:
# best score is the avg score of this estimator

In [342]:
lo=Lasso()
param_distributions={'alpha':[0.001,.01,.1,1,10,100]}

In [343]:

rscv=RandomizedSearchCV(estimator=lso,param_distributions=param_distributions,n_iter=3,cv=5,scoring='r2',verbose=2)
rscv

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [344]:
rscv.fit(x_train,y_train)
# due to n_iter we have 3 candidates

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [345]:
rscv.best_score_

np.float64(0.7878491878794973)

In [346]:
rscv.best_estimator_

Lasso(alpha=1)

In [347]:
y_test_pred_rscv_lasso=rscv.best_estimator_.predict(x_test)

In [348]:
r2_score(y_test,y_test_pred_rscv_lasso)

0.8293693600371324

In [349]:
# we have seen both randomizsed search and random search

In [350]:
ridge=Ridge()
param_grid={'alpha':[0.001,.01,.1,1,10,100]}
gscv_ridge=GridSearchCV(estimator=ridge,param_grid=param_grid,cv=5,scoring='r2',verbose=2)
gscv_ridge.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [351]:
gscv_ridge.best_estimator_

Ridge(alpha=10)

In [352]:
gscv_ridge.best_score_

np.float64(0.7943589846334789)

In [353]:
y_pred_grid_ridge=gscv_ridge.predict(x_test)

In [354]:
r2_score(y_test,y_pred_grid_ridge)

0.8354145247502054

In [355]:
# ridge randomized search cv same code repeat

In [356]:
#elastic net

In [357]:
model=ElasticNet()
param_grid={'alpha':[0.001,.01,.1,1,10,100],
            'l1_ratio':[0.1,0.4,0.9]}
model=GridSearchCV(estimator=model,param_grid=param_grid,cv=5,scoring='r2',verbose=2)
model.fit(x_train,y_train)
model.best_estimator_
model.best_params_
y_net_predict=model.predict(x_test)
r2_score(y_test,y_net_predict)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s

0.8345726087080977

In [358]:
# elastic net randomized search cv

In [359]:
model=ElasticNet()
param_distributions={'alpha':[0.001,.01,.1,1,10,100],
            'l1_ratio':[0.1,0.4,0.9]}
model=RandomizedSearchCV(estimator=model,param_distributions=param_distributions,n_iter=2,cv=5,scoring='r2',verbose=2)
model.fit(x_train,y_train)
model.best_estimator_
model.best_params_
y_net_predict=model.predict(x_test)
r2_score(y_test,y_net_predict)

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s

0.8356976438132141